### ISSUE TITLE
FPS loss when holding Wand of the Forest

### ISSUE THREAD

**Issue by codewarrior0** [Vazkii/Botania#2209]
VisualVM Sampler output:

![image](https://cloud.githubusercontent.com/assets/307683/24127924/7d375218-0d7c-11e7-8598-aa428faa595f.png)

Example build:

![image](https://cloud.githubusercontent.com/assets/307683/24127949/a9c5eb32-0d7c-11e7-8362-d94c903c54fb.png)

While holding a Wand of the Forest, my FPS drops from 45 to 9. This build has twelve Mana Spreaders equipped with Bore Lenses and two with Messenger Lenses.

Testing in a creative world isolates the problem to Mana Lenses: Twenty Mana Spreaders with Bore Lenses drops FPS from 110 to 55. When the bore lenses are removed, there is no FPS drop when holding the Wand.

Running Botania f9f56bd273aced9dc8829612e29e8c3ec44a3599 with Forge 13.20.0.2252

**Comment by codewarrior0** [comment]
Sampler output from creative world testing in dev environment:

![image](https://cloud.githubusercontent.com/assets/307683/24128367/829206e2-0d7f-11e7-824d-b7d4aa94dc50.png)

**Comment by codewarrior0** [comment]
No, I am not using composite lenses. Yes, it's weird that it's hitting that codepath, but the problem won't be addressed there - the FPS loss will still affect composite lenses. In fact, I switched all of the lenses out for composite ones and the problem got even worse!

**Comment by williewillus** [comment]
wait wut I swear I fixed this in 1.10 branch...did it get lost in the merge?

**Comment by Tamaized** [comment]
@williewillus I was thinking the exact same thing

**Comment by codewarrior0** [comment]
That's not the right fix. The problem still exists when using composite lenses.

**Comment by codewarrior0** [comment]
Actually, never mind. The FPS drop is still there with composite lenses, but it's not nearly as bad as before.
