### ISSUE TITLE
Bonemeal + Floral Powder -> Floral Fertilizer recipe not working

### ISSUE THREAD

**Issue by qrss** [Vazkii/Botania#2439]
Forge version: 14.23.0.2538
Botania version: r1.10-350

Steps to reproduce:
1. Put 1x1 Bonemeal and 4x1 Floral White Powder in the crafting grid

What I expected to happen: Able to craft Floral Fertilizer

What happened instead: Unable to craft Floral Fertilizer

**Comment by robbcrg** [comment]
This appears to be caused by a forge issue. Light Blue Powder from Light Blue Petals also fails. But NOT all powders do. For me Red, orange, Yellow and Light Blue failed -- all others worked (pestle mortar + petal). Same issue if using the flowers instead of petal.  I did not notice or test other failures.

Multiplayer mode : Single player seems OK.

The recipe is shown (if JEI is loaded), and the powder is available in Creative Mode.

Tested with ONLY Botania and Baubles mods loaded and in a new world with default Botania configurations. Items granted via GameMode 1 and crafting under GameMode 0 using character inventory.

Using Light Blue Petal for my tests I tried the varies Forge libraries I had readily available that worked well enough I did not notice this issue until I needed a light blue powder:

So somewhere after 2509 and on or before 2522 is when it stopped working for me (light blue anyway). No obvious errors in the logs.

Forge 2494: OK
Forge 2509: OK
Forge 2522: Fails
Forge 2537: Fails
Forge 2538: Fails
Forge 2540: Fails

**Comment by robbcrg** [comment]
Updated report to fix error where 2522 was listed as failed when it actually worked.

**Comment by robbcrg** [comment]
Update:

I tested a few more forges and found the latest version that worked was 2531. Note there is no 2530 Forge on their web site.

Here is my updated list using Light Blue Petal as an example. Recall that not every petal fails.

Forge 2494: OK
Forge 2509: OK
Forge 2522 : OK
Forge 2529: OK
Forge 2531: OK
Forge 2532: Fails
Forge 2534: Fails
Forge 2537: Fails
Forge 2538: Fails
Forge 2540: Fails - Latest as of this posting

**Comment by williewillus** [comment]
keep an eye on https://github.com/MinecraftForge/MinecraftForge/issues/4516

**Comment by robbcrg** [comment]
Thank you, monitoring: 4516

**Comment by williewillus** [comment]
does this still happen in forge 2542+?

**Comment by qrss** [comment]
The Floral Fertilizer recipe works in 2544.

**Comment by williewillus** [comment]
so this is fixed now?

**Comment by robbcrg** [comment]
No. I still have the powder issue on:

2544
2550 (latest)

I tested on a subset of the prior colors: It still fails for Light Blue, Yellow and Orange. But works for Cyan, This is the same as on 2521.

**Comment by robbcrg** [comment]
YES: Improved testing sequence indicates that 2550 works fine for powders.
Also verified the floral fertilizer works in 2550.

2544 : Fails
2550 (latest) : WORKS


Note: Prior testing methodology failed to verify the Server restarted with the proper Forge. The new testing sequence confirms the client and server loaded the desired Forge version.
