### ISSUE TITLE
Flugel Tiara's wings do not render properly. (1.15.2)

### ISSUE THREAD

**Issue by levilips123** [Vazkii/Botania#3259]
Version Information
Forge version:  31.1.41
Botania version:  r1.15-382

Steps to reproduce:
1.  Take any kind of Flugel Tiara.
2. Put it in the head slot.
3. Observe the rendering.

What I expected to happen:
I expected the wings to spread from under the shoulders.
What happened instead:
The wings were in places you wouldn't normally imagine wings on a human
This is how they look:
![2020-04-21_18 04 03](https://user-images.githubusercontent.com/37983569/79883371-7ff54880-83fc-11ea-8bc4-0b93ba3ea34a.png)
![2020-04-21_18 04 17](https://user-images.githubusercontent.com/37983569/79883389-8683c000-83fc-11ea-9182-05a9fd5d47d3.png)
![2020-04-21_18 04 39](https://user-images.githubusercontent.com/37983569/79883403-8b487400-83fc-11ea-98bc-ac9eeadda38a.png)
![2020-04-21_18 03 13](https://user-images.githubusercontent.com/37983569/79883299-68b65b00-83fc-11ea-8889-f0a086987d72.png)
![2020-04-21_18 03 54](https://user-images.githubusercontent.com/37983569/79883328-710e9600-83fc-11ea-96e2-c1baae3e8691.png)
![2020-04-21_18 04 59](https://user-images.githubusercontent.com/37983569/79883420-93081880-83fc-11ea-9c6a-d9a0e95ddb67.png)
![2020-04-21_18 05 20](https://user-images.githubusercontent.com/37983569/79883433-969b9f80-83fc-11ea-877d-30ded52b58ed.png)
![2020-04-21_18 05 31](https://user-images.githubusercontent.com/37983569/79883441-99969000-83fc-11ea-9684-4463905ff5f4.png)

It kinda is not that big of a deal since you can put a cosmetic over it and the wings don't render anymore but i'd like to have actual Phoenix wings that don't come out of my ankles. Pls.

**Comment by MrReps** [comment]
Hi,
I would like to add something on the Botania-r1.15-384 version i have the same bug in solo, and in Mulyi (on a serveur) i'm kicked out of it when i put it in the head slot. So i can't play with it :(.
kind regard,

**Comment by Awesomespore** [comment]
I can confirm that this is issue is present for me as well.
![2020-06-10_17 57 26](https://user-images.githubusercontent.com/59407684/84232174-e0268200-ab43-11ea-9ce4-a509dd14b576.png)
(wings are angled forwards instead of backwards)

**Comment by Alwinfy** [comment]
It's still the `master` branch rn 😅

**Comment by Hubry** [comment]
Looks like all the wings are fixed now?

**Comment by Johnyknowhow** [comment]
This is still happening on my 1.15.2 server with Botania r1.15-388, which seems to be the latest build for 1.15.2 (as of writing, of course.)

I'm running the mod within the Valhelsia 2 (2.2.8) modpack, for reference.  

![image](https://user-images.githubusercontent.com/22043505/91389192-ae8d9080-e7ed-11ea-86e7-c56debe91d96.png)

Re-open? Or is there something else I'm missing?

**Comment by williewillus** [comment]
the fix is in 1.16
