### ISSUE TITLE
Botania r1.15-382 Minecraft 1.15.2 manasteel sheers not working like they used to

### ISSUE THREAD

**Issue by kylekoch012186** [Vazkii/Botania#3262]
#Version Information
Forge version:  31-1-43
Botania version:  r1.15-382

# Further Information
Not an issue that causes a crash.

What I expected to happen: Using Manasteel Shears on Vines, Leaves, Grass or Tall Mystical Flowers (mystical agriculture) expected to harvest item.

What happened instead:  Using manasteel shears just breaks the items with nothing to collect.

Side notes:  Manasteel sheers only work on sheep.  I have a dedicated kitchen-sink server up and running for friends and family.  If you would like to see it with my setup then I can send you the mod-stack for twitch and server details.

**Comment by williewillus** [comment]
fixed (mostly) in the next version

**Comment by ClaudiusMinimus** [comment]
This issue persists in Botania-r1.15-384. Also affects vines

**Comment by williewillus** [comment]
see bottom of #3275, nothing we can do anymore sadly.
