### ISSUE TITLE
Floating Flower crashes client when punched

### ISSUE THREAD

**Issue by Serifina** [Vazkii/Botania#4090]
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-434

### Modloader version

40.1.54

### Modpack info

https://www.curseforge.com/minecraft/modpacks/the-phoenixs-magics-and-goodies

### The latest.log file

https://gist.github.com/Serifina/ed5fc8702e1261368b4d853a684b279f

### Issue description

Client crashes when punching a floating hopperhock with an empty hand. Does not when breaking with a shovel.

### Steps to reproduce

1. Place floating flower.
2. Punch floating flower.

**Comment by williewillus** [comment]
Does it happen with just botania and its dependencies?

**Comment by TheRealWormbo** [comment]
I originally notified Serifina of this crash, and yes it does also crash with just Forge, Patchouli (1.18.2-71.1), Curios (1.18.2-5.0.7.1) and Botania (1.18.2-434). Looks like it's yet another issue with the Forge block rendering pipeline, as setting `experimentalForgeLightPipelineEnabled = false` fixes the issue.
It seems to generally happen with any type of slower breaking in survival, e.g. using an unenchanted wooden shovel crashes as well.

**Comment by williewillus** [comment]
Hm, forge reverted the change in later versions, so this should be fixed. I'll look later.

**Comment by Charismara** [comment]
Same Problem here :S 
is there a fix in progress?

**Comment by williewillus** [comment]
Update forge and botania to the absolute latest versions possible. This should be fixed already.

**Comment by williewillus** [comment]
Failing that, turn off the config option wormbo mentioned above.

**Comment by Serifina** [comment]
I tested it, just now, with the latest Forge with the experimental lighting pipeline on and off. It still crashes with it on : https://gist.github.com/Serifina/f7376eb943926573ce383e4425431340

And does not with it off. This is with 40.1.68, but the revert was in .54, which was the one used in the original crash I reported.

**Comment by Charismara** [comment]
> Update forge and botania to the absolute latest versions possible. This should be fixed already.

I'm using Forge 40.1.68 and Botania 1.18.2-434 but it still crashes on punches
