### ISSUE TITLE
[Neoforge][1.21.1]Summary of Known Bugs

### ISSUE THREAD

**Issue by FortyTwoCn** [Vazkii/Botania#4885]
### Mod Loader

NeoForge

### Minecraft Version

1.21.1

### Botania version

1.21.1-449-SNAPSHOT

### Modloader version

Neoforge 197

#### 1.Rendering issues
~~①. Some items fail to render their contained properly~~ **(Fixed)**
<img width="506" height="351" alt="Image" src="https://github.com/user-attachments/assets/d07e0101-10e3-43ec-b4d5-1b63a556dbe1" />
②. When the mouse hovers over the Runic Altar, red and green stripes appear on the right side of the screen
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/d40a42c5-25c6-4122-bd3a-0e3e2fed80d8" />
③.When there is mana in the mana pool, the mana rendering is incorrect
<img width="937" height="590" alt="Image" src="https://github.com/user-attachments/assets/f9204348-116f-4d5f-9b66-923f8092954b" />
~~④.Sparks are not displaying  ~~ **(Fixed)**
<img width="1209" height="910" alt="Image" src="https://github.com/user-attachments/assets/427205b7-4feb-49ac-b027-237e4155f20b" />
⑤.Incorrect water rendering in the Apothecary
<img width="469" height="512" alt="Image" src="https://github.com/user-attachments/assets/517386db-7f20-44ff-b986-7a6ef5fb600d" />

#### 2.Bug
①When using the Runic Altar for synthesis, the crafting materials are not consumed but instead drop to the ground.
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/72729ccd-30d0-48a0-8d35-cf3beda07fc2" />
②"Right-click with empty hand to return to last crafting" ignores empty hand condition （Including the Petal Apothecary）
https://github.com/user-attachments/assets/4dd6273d-5a0c-4b60-beec-75e81880254a
③Terrestrial Agglomeration Plate Cannot craft

~~④Starfield Creator is more effective during the day than at night~~ **(invalid)**
https://github.com/user-attachments/assets/2f8d167a-aaa9-4ed3-9a32-77aa318ad0e2

~~⑤ Perhaps the MOD tab in Creative mode shouldn't appear on the first page? ~~ **(Fixed)**
<img width="539" height="155" alt="Image" src="https://github.com/user-attachments/assets/999ddb7b-a963-46d7-8bf9-4e2157d7eaf1" />

#### 3.Awaiting further testing

Sorry for my English .This issue may be continuously updated with newly discovered problems , thank you to all the developers for their contributions to this mod

**Comment by TheRealWormbo** [comment]
Quick follow-up:

- 1.1 should be fixed already.
- For 1.2-1.5 I don't even know where to start searching for where those might come from. May need some external help to figure out these issues.
- 2.1 and 2.2 are now on my near-term ToDo list.
- 2.3 may or may not get an intermediary fix, as we have plans for a potentially bigger rework of how Botania defines its multi-block structures.

**Comment by FortyTwoCn** [comment]
> Quick follow-up:
> 
> * 1.1 should be fixed already.
> * For 1.2-1.5 I don't even know where to start searching for where those might come from. May need some external help to figure out these issues.
> * 2.1 and 2.2 are now on my near-term ToDo list.
> * 2.3 may or may not get an intermediary fix, as we have plans for a potentially bigger rework of how Botania defines its multi-block structures.

Updating one of my mistakes: the Alfheim Portal works, but the Terrestrial Agglomeration Plate still doesn't. Sorry.


And add a bug
2-④Starfield Creator is more effective during the day than at night
https://github.com/user-attachments/assets/2f8d167a-aaa9-4ed3-9a32-77aa318ad0e2

**Comment by TheRealWormbo** [comment]
Another update:
1.4 was a reasonably easy fix. Apparently the sprite was merely rotated 180° away from the player.

I can't confirm the Starfield Generator bug. Do note that the star particles take a while to show up and vanish again. It could also be a conflict with another mod you are running.

~~Not sure what's causing 2.5, as that was an issue in certain 1.20.1 packs already. something mixes up the tab order, but I don't know what part Botania plays in that, other than just adding its tab at all.~~ Scratch that, I found and fixed the issue.

**Comment by FortyTwoCn** [comment]
> Another update: 1.4 was a reasonably easy fix. Apparently the sprite was merely rotated 180° away from the player.
> 
> I can't confirm the Starfield Generator bug. Do note that the star particles take a while to show up and vanish again. It could also be a conflict with another mod you are running.
> 
> ~Not sure what's causing 2.5, as that was an issue in certain 1.20.1 packs already. something mixes up the tab order, but I don't know what part Botania plays in that, other than just adding its tab at all.~ Scratch that, I found and fixed the issue.

Add a bug
2-⑥Black Lotus cannot be properly converted into mana
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/644bb900-6b0e-4ed7-bb9d-e03cdc634195" />

**Comment by TheRealWormbo** [comment]
Black Lotus must be dissolved in mana, i.e. the pool must not be empty.

**Comment by TheRealWormbo** [comment]
That, too, is intentional for a while already. Please compare unexpected behavior to how it works in the 1.20.1 version before reporting.

**Comment by FortyTwoCn** [comment]
> That, too, is intentional for a while already. Please compare unexpected behavior to how it works in the 1.20.1 version before reporting.

I'm sorry to bother you, before 1.21.1, the highest version I've played was 1.16.5. Sorry.

**Comment by TheRealWormbo** [comment]
More data points for render issues.
1. The obsidian overlay of the Mana Enchanter exhibits a similar issue as several other shader surfaces: <img width="854" height="480" alt="Image" src="https://github.com/user-attachments/assets/5945a4e2-2d6a-4106-9917-cd3e78b23627" />
2. The wand HUD overlay of the enchanter has a similar screen corruption issue as the Runic Altar's, presumably that's caused by the pie progress chart: <img width="854" height="480" alt="Image" src="https://github.com/user-attachments/assets/57569e76-c190-4523-b7fb-a0e25e3f11c5" />
3. Actually a good thing: The Minecart with Mana Pool shows the same incorrect mana texture as any mana pool blocks. That means its render logic works as intended, showing the mana pool the same way the stationary pool is rendered. <img width="854" height="480" alt="Image" src="https://github.com/user-attachments/assets/1df3a4f5-1c77-4bf3-b3a7-3987741af9a7" />

**Comment by TheRealWormbo** [comment]
Update on the runic altar recipe issue: For some reason it fixes itself when using `/reload` to reload data packs. As far as I can tell, the ingredient using tag `c:gems/mana_diamond` does not recognize any items before the reload.

[edit] …and fixed. It was caused by trying to validate recipes too early after world load.

**Comment by TheRealWormbo** [comment]
Further updates:
- mana rendering for pools works again
- same for fluid in petal apothecary
- same for obsidian overlay of the mana enchanter
- Terrestrial Agglomeration Plate now properly recognizes its multi-block structure and thus works again

(progress pie for mana enchanter and runic alter are still broken)

**Comment by TheRealWormbo** [comment]
> The Ender Hand does not seem to function properly.

Can you explain what about the Hand of Ender doesn't work? It seems to open the ender chest inventory just fine.

**Comment by anoomolu** [comment]
No issues with the Hand of Ender either, just a reminder you need a Mana tablet or equivalent to open it.

**Comment by FortyTwoCn** [comment]
> > The Ender Hand does not seem to function properly.
> 
> Can you explain what about the Hand of Ender doesn't work? It seems to open the ender chest inventory just fine.

I couldn't reproduce this issue in a Neoforge environment with only this single mod, so the problem might be related to other optimization mods

**Comment by FortyTwoCn** [comment]
> > The Ender Hand does not seem to function properly.
> 
> Can you explain what about the Hand of Ender doesn't work? It seems to open the ender chest inventory just fine.

By the way, it seems that Tiny Potato can cause client crashes. At least this issue exists when the Sodium mod is present.

**Comment by TheRealWormbo** [comment]
Yes, just got fixed for #4894.

**Comment by FortyTwoCn** [comment]
> Yes, just got fixed for [#4894](https://github.com/VazkiiMods/Botania/issues/4894).

<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/22efcc76-dca6-4037-a357-1edec2379c52" /> However, his textures are missing, but that's not a big issue anymore Thanks

**Comment by TheRealWormbo** [comment]
As far as I can tell, we now have separate tickets for anything still open in this thread. I recommend updating your Botania version and then reporting new issues separately, as anoomolu did.

Also, fair warning: Future work on the 1.21.1 version *will* contain changes that break compatibility with thew current state. If anything, only world updates directly from 1.20.1 will be supported.

**Comment by TheRealWormbo** [comment]
Closing this as "done" for now. Please make individual reports for any other bugs you find, as that's easier for us to track in terms of what already got fixed.
